### ISSUE TITLE
v12.6.0: plain .js/.mjs/.cjs unparseable — realized regression of #1654 (tree-sitter 0.26.9 rejects TS-only node types in shared jsts query)

### ISSUE THREAD

**Issue by Letsrollamigo** [thedotmack/claude-mem#2750]
# Bug: plain `.js` / `.mjs` / `.cjs` now fully unparseable — the regression predicted in #1654 has occurred (tree-sitter 0.26.9 hard-rejects TS-only node types in the shared `jsts` query)

**Repo:** https://github.com/thedotmack/claude-mem
**Version:** 12.6.0
**tree-sitter CLI:** 0.26.9
**Component:** MCP search server (`scripts/mcp-server.cjs`), tree-sitter smart-file tooling
**Platform:** macOS arm64, runtime = bun 1.3.14 (root cause is platform-independent)

## This is the realized regression from #1654
Issue #1654 (closed NOT_PLANNED, 2026-04-10) called this exactly:

> Relies on tree-sitter silently ignoring invalid patterns. **If tree-sitter changes to fail on unrecognized node types, all `.js` file parsing breaks.**

That has now happened. tree-sitter 0.26.9 no longer silently ignores unknown
node types — it aborts query compilation. So every plain-JS file now fails.
Note the first offender is actually `type_identifier` (used for the class name
in the shared query), not only the three declarations listed in #1654.

## Summary
Any plain JavaScript file (`.js`, `.mjs`, `.cjs`) silently returns
`Could not parse <file>. File may use an unsupported language or be empty.`
from `smart_outline` (and yields no symbols in `smart_search`). TypeScript and
JSX/TSX (`.ts`, `.tsx`, `.jsx`) work fine. The failure is total for vanilla-JS
codebases (e.g. legacy monoliths, Node CJS services).

## Root cause
The extension→grammar map sends plain JS to the `javascript` grammar:

```js
const EXT_MAP = { ".js":"javascript", ".mjs":"javascript", ".cjs":"javascript",
                  ".jsx":"tsx", ".ts":"typescript", ".tsx":"tsx", ... }
```

But all three of `javascript` / `typescript` / `tsx` share one tags query
(`group "jsts"`):

```scm
(function_declaration name: (identifier) @name) @func
(lexical_declaration (variable_declarator name: (identifier) @name
  value: [(arrow_function) (function_expression)])) @const_func
(class_declaration name: (type_identifier) @name) @cls          ; <-- TS-only
(method_definition name: (property_identifier) @name) @method
(interface_declaration name: (type_identifier) @name) @iface    ; <-- TS-only
(type_alias_declaration name: (type_identifier) @name) @tdef    ; <-- TS-only
(enum_declaration name: (identifier) @name) @enm                ; <-- TS-only
(import_statement) @imp
(export_statement) @exp
```

`tree-sitter query` validates the **entire** query against the grammar and
aborts if any node type is unknown. The pure `javascript` grammar has no
`type_identifier`, `interface_declaration`, `type_alias_declaration`, or
`enum_declaration`, so the query fails to compile and `execFileSync` throws. The
server catches it and returns the generic "Could not parse" message — masking the
real error.

## Reproduction
```bash
cd ~/.claude/plugins/cache/thedotmack/claude-mem/12.6.0
printf 'function f(){return 1}\nclass C{m(){}}\n' > /tmp/x.js

# extract the shared jsts query into /tmp/jsts.scm, then:
node_modules/.bin/tree-sitter query -p node_modules/tree-sitter-javascript /tmp/jsts.scm /tmp/x.js
#   Error: Query compilation failed
#   Caused by: Query error at 4:27. Invalid node type "type_identifier"

# same query against the tsx grammar succeeds:
node_modules/.bin/tree-sitter query -p node_modules/tree-sitter-typescript/tsx /tmp/jsts.scm /tmp/x.js
#   pattern 0, capture: func ...
```

Via the MCP tool: `smart_outline { file_path: "/any/plain.js" }` →
`Could not parse ...`.

## Fix (verified)
The `tsx` grammar is a superset that parses plain JS **and** JSX, and the `jsts`
query is fully valid against it. Route plain JS through `tsx`:

```diff
- ".js":"javascript", ".mjs":"javascript", ".cjs":"javascript",
+ ".js":"tsx", ".mjs":"tsx", ".cjs":"tsx",
```

After this, a real 10,755-line vanilla-JS monolith outlines correctly
(334 symbols) where it previously returned "Could not parse".

### Alternatives
- Keep the `javascript` mapping but give it a JS-specific query (class names are
  `(identifier)`, drop the `interface_/type_alias_/enum_declaration` patterns).
- Make the query runner tolerant: compile patterns individually and skip the ones
  the grammar rejects, instead of failing the whole query. This also future-proofs
  every other shared query/grammar pair.

## Secondary observation (not the cause, but worth a look)
`tree-sitter-css`'s ESM loader (`bindings/node/index.js`) does
`await import('…/<name>.node')`, which bun's runtime rejects
(`To load Node-API modules, use require()/process.dlopen`). This does **not**
affect the smart tools (they go through the `tree-sitter` CLI, not the package's
JS binding), but it will bite anything that `require()`s the grammar package
directly under bun. The `tree-sitter-scss` loader (plain CJS `node-gyp-build`)
is the bun-safe pattern.

**Comment by Letsrollamigo** [comment]
### Suggested fix (patch)

Three options, in order of robustness. I verified **Option B** end-to-end on a real 10,755-line vanilla-JS file (0 symbols → 334 symbols).

#### Option A — give plain JS its own query (most correct)
The shared `jsts` query is invalid against `tree-sitter-javascript`. Split it so `.js`/`.mjs`/`.cjs` use a JS-only query. In `src/services/smart-file-read/parser.ts`:

```diff
 const QUERIES = {
   jsts: `
 (function_declaration name: (identifier) @name) @func
 (lexical_declaration (variable_declarator name: (identifier) @name
   value: [(arrow_function) (function_expression)])) @const_func
 (class_declaration name: (type_identifier) @name) @cls
 (method_definition name: (property_identifier) @name) @method
 (interface_declaration name: (type_identifier) @name) @iface
 (type_alias_declaration name: (type_identifier) @name) @tdef
 (enum_declaration name: (identifier) @name) @enm
 (import_statement) @imp
 (export_statement) @exp
 `,
+  js: `
+(function_declaration name: (identifier) @name) @func
+(lexical_declaration (variable_declarator name: (identifier) @name
+  value: [(arrow_function) (function_expression)])) @const_func
+(class_declaration name: (identifier) @name) @cls
+(method_definition name: (property_identifier) @name) @method
+(import_statement) @imp
+(export_statement) @exp
+`,
 }

 function getQueryKey(language) {
-  if (language === "javascript" || language === "typescript" || language === "tsx") return "jsts";
+  if (language === "typescript" || language === "tsx") return "jsts";
+  if (language === "javascript") return "js";
   ...
 }
```
Note: class names in `tree-sitter-javascript` are `(identifier)`, not `(type_identifier)`; and `interface_/type_alias_/enum_declaration` don't exist there.

#### Option B — route plain JS through the `tsx` grammar (smallest change, verified)
`tsx` is a superset that parses plain JS *and* JSX, and the existing `jsts` query is valid against it. Just change the extension map:

```diff
- ".js": "javascript", ".mjs": "javascript", ".cjs": "javascript",
+ ".js": "tsx", ".mjs": "tsx", ".cjs": "tsx",
```

#### Option C — make the query runner tolerant (future-proofs every grammar/query pair)
In `runBatchQuery`, compile patterns individually and skip the ones the grammar rejects instead of failing the whole query (and log the skip rather than swallowing it). This prevents the *silent* empty-result failure mode that masked this bug.

---

### Why it broke now
`tree-sitter` CLI **0.26.9** no longer silently ignores unknown node types — it aborts query compilation:
```
Error: Query compilation failed
Caused by: Query error at 4:27. Invalid node type "type_identifier"
```
This is exactly the failure predicted in #1654 (closed `wontfix`). The first offender is `type_identifier` (class name in the shared query), which fails before the three TS-only declarations listed there.

### Suggested labels
`bug`, `severity:high`, `component:mcp` (or `component:summarizer`). I couldn't apply them myself (no triage permission).

**Comment by thedotmack** [comment]
Consolidating into #2786 (plan-13). The root cause and fix sequencing are tracked there alongside the rest of the cluster — please follow that issue for progress.
