### ISSUE TITLE
Tracking: 8 PRs ready for review (Windows / packaging / supervisor cluster)

### ISSUE THREAD

**Issue by YOMXXX** [thedotmack/claude-mem#2601]
## TL;DR

**10 self-contained PRs** targeting **6 release-blocking issue clusters**. Combined effect: every Windows install since v13.0.1 should boot cleanly, the worker bundle drops ~720 KB and 68 OAuth provider URLs (with zod inlined for install-fragility), the marketplace install no longer ships dead deps, a year-long PID-reuse deadlock gets a guard, and the observer death-loop (issue #2468) is closed.

| Metric | Value |
|---|---|
| PRs | 10 |
| Issues closed (full) | 16 |
| Issues closed (partial) | 1 (#2407) |
| Worker bundle | 3782 KB → ~3389 KB (after #2596 −720 KB + #2610 +329 KB; net −10%) |
| OAuth provider URLs in bundle | 94 → 26 |
| Greptile reviews | 10/10 PRs; 3 already 5/5, 5 had fixup commits applied (re-review pending), 2 awaiting first pass |
| Author | @YOMXXX |

This issue exists so the PRs can be reviewed and merged together as a coordinated set without losing the cross-PR context.

---

## PR-by-PR

| PR | Title | Closes | Greptile | Δ |
|---|---|---|---|---|
| #2592 | `fix(build)` add transcript-watcher.cjs build target | #2450 | ✅ 5/5 | +83 −0 |
| #2593 | `fix(chroma)` escape cmd.exe metacharacters in uvx args on Windows | #2585, #2591, #2495, #2429, #2405 | 4/5 + fixup ⏳ | +22 −2 |
| #2594 | `fix(mcp)` replace sh launcher with cross-platform node -e | #2461 | 3/5 + fixup ⏳ | +20 −3 |
| #2595 | `chore(scripts)` drop sync-to-marketplace.sh + harden sync-marketplace.cjs | #2570 (bash half) | 3/5 + fixup ⏳ | +135 −78 |
| #2596 | `refactor(build)` externalize better-auth from worker/server-beta bundles | #2584 | ✅ 5/5 + fixup ⏳ | +449 −825 |
| #2597 | `fix(build)` populate plugin/node_modules during build | #2407 (partial) | 3/5 + fixup ⏳ | +58 −0 |
| #2598 | `fix(hooks)` replace fragile $SHELL -lc PATH probe with printenv-first pattern | #2589, #2588, #2461, #2439 (PATH half — see #2613) | ✅ 5/5 | +6 −6 |
| #2599 | `fix(supervisor)` make Windows captureProcessStartToken actually return a token | #2578 | 4/5 + fixup ⏳ | +225 −192 |
| #2602 | `fix(observer)` truncate oversized prompt fields + drop overflow from hard-stop | #2468 | (awaiting first pass) | +269 −219 |
| #2610 | `fix(build)` inline zod into worker / server-beta / context-generator bundles | #2437 | (awaiting first pass) | +713 −556 |

⏳ = fixup commits applied, Greptile re-review has been pending 17+ hours — may need a maintainer manual re-trigger via the `Re-trigger Greptile` link on each PR.

---

## Recommended merge order

```
Independent (any order — no file overlap):
  ┌── #2592 transcript-watcher build target
  ├── #2593 Windows cmd.exe metacharacter escape
  ├── #2594 mcp-search node-e launcher
  ├── #2595 sync-marketplace cross-platform
  ├── #2598 hooks printenv PATH probe
  ├── #2599 Windows PID-token
  ├── #2602 observer prompt truncation + soft-overflow
  └── #2610 inline zod into worker bundle (touches scripts/build-hooks.js
            externals — coordinates with #2596 if both land same release;
            #2596 removes better-auth from externals, #2610 removes zod;
            different keys in the same array, no merge conflict)

Pair (ship in the same release cycle):
  #2596 better-auth external
      │
      └─► #2597 build install plugin/node_modules
          (without #2597, #2596 breaks the dev workflow because the
           externalized better-auth has nowhere to resolve from at runtime)
```

All 10 PRs are mergeable independently from a code-conflict standpoint (different files, or different functions in the same file). The #2596 / #2597 dependency is a runtime concern, not a merge-conflict one. #2596 and #2610 both edit `scripts/build-hooks.js` externals but in disjoint keys.

---

### Windows shell / hooks (5 issues, 2 PRs)

- **#2593** silences `MCP error -32000: Connection closed` on every Chroma sync on Windows. Root cause: `cmd.exe` parses the unquoted `<` / `>` in `protobuf<7` / `onnxruntime>=1.20` as I/O redirection metacharacters before launching uvx. Escapes `^<>&|%` on the Windows branch only; `%` was added in the fixup after Greptile flagged that user-supplied `chromaApiKey` could contain `%` and get silently env-expanded.
- **#2598** kills `printf: write error: Permission denied` noise on every hook invocation. Root cause: `$($SHELL -lc 'echo $PATH' 2>/dev/null)` fails in Git Bash when stdin isn't a TTY. Replaced with the same `printenv PATH` + `$SHELL -lc 'printf %s "$PATH"'` fallback that `codex-hooks.json` already uses in production. **Scope clarification**: @kls06541's review on #2598 surfaced that #2439's report actually attributes the symptom to a separate `nested-pipe` construct in the same hooks. #2598 fixes the PATH probe half only; the nested-pipe remediation is tracked in #2613 pending Win11 + Node 24.x reproduction. The `closes #2439` line is optimistic until that verification.

### Cross-platform MCP launcher (1 issue, 1 PR)

- **#2594** replaces `sh -c '...exec node ...'` with `node -e '...same logic in JS...'`. Windows has no `sh` so the old launcher was a hard block. Fixup adds POSIX SIGTERM/SIGINT/SIGHUP forwarding + correct signal-death exit code via `removeAllListeners + process.kill(self, sig)` — verified with a sleep-child smoke test (launcher exits 143 when SIGTERM'd).

### Packaging (4 issues, 5 PRs)

- **#2592** `claude-mem transcript watch` was silently broken since v13.x because `runtime.ts:230` hard-references `plugin/scripts/transcript-watcher.cjs` but `scripts/build-hooks.js` never compiled it. Adds the build target + a thin entry that dispatches argv into the existing `runTranscriptCommand`. Fixup added `zod` to external + a 200 KB bundle-size guard.
- **#2595** removes the legacy `sync-to-marketplace.sh` (Windows incompatibility) and adds `--dry-run` + opt-in `--force-delete` + a `PRESERVE_PATTERNS` allowlist that protects user env / secrets from `rsync --delete`. Fixup addressed all 5 Greptile findings including a real bug where `--dry-run` alone (no `--force-delete`) was skipping rsync entirely.
- **#2596** bundles **~720 KB and 68 OAuth provider hostnames** out of `worker-service.cjs` by externalizing `better-auth*`. Root cause: `BetterAuthRoutes.ts` uses `await Promise.all([import('better-auth/node'), import('./auth.js')])` hoping esbuild would tree-shake, but `bundle:true` + no `splitting` inlines literal-path dynamic imports as deferred CJS factories. Now resolved at Node runtime via `plugin/node_modules`. Fixup made the version pin derive from root `package.json` (throws on missing — no silent fallback).
- **#2597** populates `plugin/node_modules` during build so the externalized `better-auth` / `zod` / tree-sitter grammars can resolve at runtime. Without `--ignore-scripts` (deliberately) so `prebuild-install` can download prebuilt `.node` bindings instead of triggering node-gyp on niche archs. Fixup added `shell: process.platform === 'win32'` for the Windows `.cmd` batch wrapper, anchored `cwd` to `__dirname`, and switched to `node:child_process`.
- **#2610** closes the recurring `Cannot find module 'zod/v3'` regression (#2437) that has shipped on v13.0/v13.1/v13.2/v13.3. Inlines `zod` into the three Node-platform bundles (worker, server-beta, context-generator) the same way `mcp-server.cjs` already does it. Bundle cost +329 KB worker, +332 KB server-beta. Complementary to #2596/#2597: #2596 externalizes large rarely-used `better-auth` to shrink the bundle; #2610 inlines small hot-path `zod` to remove the install-fragility surface entirely. zod has no native bindings and no startup dynamic-loading expectations, so inlining is safe. The existing assertion at `build-hooks.js:269-274` (which already guards `mcp-server.cjs` against zod regression) provides the test harness for the same pattern across the new bundles.

### Supervisor (1 issue, 1 PR)

- **#2599** Until this PR, `captureProcessStartToken()` returned `null` on Windows, which made `verifyPidFileOwnership` short-circuit at `currentToken === null → return true`, completely disabling PID-reuse detection. When the worker died and Windows reassigned its PID (#2578 reports `SignalRgbLauncher.exe`), `claude-mem status` reported the worker as healthy and `start` refused to launch a fresh one. Now uses PowerShell `Get-Process` to compose a `(StartTime.Ticks | ProcessName)` token. Every failure mode falls back to the prior null-returning behavior, so worst case is no regression. Fixup added the idiomatic `result.error || result.status !== 0` spawnSync guard on both Windows and POSIX branches.

### Observer (1 issue, 1 PR)

- **#2602** closes the **observer death-loop** in #2468. A 130k-char Read tool result blew the observer model's context window → SDK aborts with `'overflow'` → `GeneratorExitHandler.isHardStopReason` returns true → `clearPendingForSession` wipes every queued observation including the unrelated ones queued after the offending Read → new observations re-trigger the generator → cycle repeats until RestartGuard trips. The fix has two layers: (1) `buildObservationPrompt()` now caps each `<parameters>` / `<outcome>` field at 16k chars with a head + tail slice and an explicit `<elided chars="..." />` marker the model is told to respect; (2) `'overflow'` is removed from `isHardStopReason()`, so if a residual cause (e.g. an oversized conversation history) still trips "prompt is too long" the queued observations are preserved by the restart path instead of cleared. RestartGuard caps consecutive overflow→restart cycles so we can't loop forever.

---

## What's intentionally NOT in this batch

| Issue | Why deferred |
|---|---|
| #2574 summarizer cross-session contamination | Depends on observer prompt scaffolding from #2602 (the `<elided/>` marker + grounding hint). Will be a follow-up PR adding a post-process grounding validator (fact references must exist in source observation). |
| #2407 npm tarball half | Solved partially in #2597 (dev workflow + marketplace path). Adding `plugin/node_modules` to `package.json#files` for the npm tarball is a separate review concern (tarball size, cross-arch publish). |
| #2613 nested-pipe `_P=$({...}|while...)` on Win11 | Surfaced during #2598 review by @kls06541; my Win10 + macOS reproductions don't trip it. mktemp temp-file rewrite is ready; waiting on Win11 + Node 24.x reproduction before opening. |
| #2600 hooks `tr ' ' ':'` corruption on Windows paths with spaces | Pre-existing concern surfaced by Greptile on #2598; spans `hooks.json` and `codex-hooks.json` so split out into its own issue. |
| D series (#2542 argon2id, #2561 postgres, #2573 server CLI, #2559 docker) | Review-only on existing PRs from @mguttmann — no new code from this fork. |
| #2435 OpenCode integration | Existing PRs #2503 / #2557 already cover it. |

---

## Risk summary

| Risk surface | Mitigation |
|---|---|
| Windows-only changes (#2593, #2599, parts of #2594/#2598) | Every Windows-specific code path preserves the pre-PR behavior as a fallback. Worst case = no-op vs. today. macOS/Linux paths smoke-tested locally. |
| Bundle externalization (#2596) | Coupled with #2597; documented in both PR descriptions. |
| Bundle inlining (#2610) | +329 KB / +332 KB on hot bundles, but removes the most-reported install regression of v13.x. zod is pure JS, used pervasively, so inlining matches `mcp-server.cjs`'s already-shipping pattern. |
| sync-marketplace breaking change (#2595) | `--force-delete` is now opt-in; documented as a migration note. |
| Observer truncation (#2602) | Existing observations that previously overflowed will now succeed with a head+tail-only view; that's strictly better than the prior "wipe entire batch" failure mode. No external API changes, no schema changes. |
| Greptile re-review pending on 5 PRs (#2593, #2594, #2595, #2596, #2597, #2599) | Every fixup commit addresses a concrete Greptile finding documented in the PR thread — no speculative changes. Re-trigger link is available on each PR; pending 17+ hours suggests bot may need manual nudge from a maintainer. |
| #2602 / #2610 awaiting Greptile first pass | Just pushed; deferred till the bot scans. |

---

## Empirical checks

All 10 PRs run `npm run build` cleanly on macOS arm64 (Node 22, npm 10). Windows behavior is deferred — but every Windows-specific change is gated on `process.platform === 'win32'` and falls back to today's behavior on failure, so the worst case is no regression.

Per-PR verification (also documented in each PR description):

- **#2593** Bundle contains `p.replace(/%/g,"%%").replace(/([\^<>&|])/g,"^$1")` after fixup
- **#2594** Sleep-child smoke test: launcher SIGTERM → child dies → launcher exits 143 (128+15)
- **#2596** Worker bundle 3782 → 3060 KB; OAuth host count 94 → 26; `grep -c better-auth` 12 → 2 (only `require()` calls)
- **#2597** `npm install` in `plugin/` adds 57 packages in 58s on macOS
- **#2598** New PATH probe yields 3626 chars of PATH including `/usr/local`
- **#2599** macOS `ps -p $pid -o lstart=` returns timestamp (POSIX path unaffected)
- **#2602** Truncation smoke test: 200k-char input → 14k-char output with `<elided chars="186k" original_size_chars="200k" />` marker; small inputs byte-identical to `JSON.stringify`
- **#2610** Worker bundle `grep -E "require\(['\"]zod(/[^'\"]*)?['\"]\)"` returns 0 hits; `grep -c 'ZodError\|ZodObject\|ZodString'` returns 7 hits (inline confirmed)

---

Tagging @thedotmack — happy to split the merge into multiple smaller releases if that's easier, or to fold in additional follow-ups if any of these uncover further concerns during review.

**Comment by YOMXXX** [comment]
Update: added **#2602** to the tracking list — `fix(observer)` truncate oversized prompt fields + drop overflow from hard-stop, closes #2468 (observer death-loop). Two-layer fix:

1. `buildObservationPrompt()` truncates each `<parameters>` / `<outcome>` field to 16k chars with head+tail slicing and an explicit `<elided chars="..." />` marker the model is told to respect.
2. `'overflow'` removed from `isHardStopReason()` so a residual context overflow no longer wipes the pending observation batch — RestartGuard caps the cycles.

The cluster count moves from 5 → 6. Total: **9 PRs / 15 issues closed**. Top of this issue refreshed with the new row and cluster description.

Three PRs are now Greptile 5/5 and ready (#2592, #2596, #2598); five have fixup commits applied and are awaiting Greptile's second pass; #2602 just landed and is awaiting first pass.

Happy to land them in whatever sequencing works for the next release — full list, dependency notes, and risk summary are at the top.

cc @thedotmack

**Comment by YOMXXX** [comment]
Updated merge-queue proposal as of 2026-05-25.

The backlog looks blocked on maintainer merge decision, not on GitHub mergeability: there are 90+ open PRs, ~68 `MERGEABLE`, and ~58 non-draft mergeable third-party PRs. To make this actionable, I would avoid reviewing everything at once and land a small, low-risk batch first.

## Batch A — merge candidates with narrow blast radius

These are small, mergeable, and address active user-facing breakage:

| PR | Why first | Notes |
|---|---|---|
| #2594 | Cross-platform MCP launcher; removes `sh -c` from `.mcp.json` | Tiny diff; Greptile 5/5 after fixups; helps Windows MCP failures. |
| #2598 | PATH-probe half of Windows hook failures | Keep scope honest: does not close nested-pipe #2613 by itself. |
| #2592 | Missing `transcript-watcher.cjs` build target | Self-contained packaging fix. |
| #2629 | Strip Bedrock/Vertex/Mantle routing env from worker subprocess | Small env-isolation fix; prevents silent infinite compression failures from #2620. |
| #2628 | Drop unsupported marketplace metadata field | One-file metadata cleanup. |
| #2630 | Uninstall removes `CLAUDE_CODE_DISABLE_AUTO_MEMORY` | Small UX correctness fix with test. |
| #2635 | Initialize ModeManager in server-beta + `CLAUDE_MEM_MODES_DIR` | Small server-beta startup fix; Greptile 5/5. |
| #2634 | Link tool_use events via contentSessionId | Focused server-beta data linkage fix; reviewed by Greptile/Codex. |

## Batch B — choose one packaging strategy before merging

The zod / node_modules fixes overlap. Suggested policy:

1. Prefer #2610 as the root fix for `zod/v3` because inlining pure-JS zod removes the runtime dependency from every install path.
2. Treat #2644 as defense-in-depth only. The author addressed the main guardrails; remaining Greptile nit is a first-run progress log before blocking `bun install`.
3. #2597 is useful for dev/marketplace-sync dependency population, but it should not be considered a full fresh-install fix if #2610 is accepted.

So I would land #2610 first, then decide if #2644 is still wanted as a self-heal fallback. Avoid landing multiple overlapping fixes without an explicit policy, or future packaging regressions will be harder to reason about.

## Batch C — reliability fixes that need explicit owner decision

| PR | Recommendation |
|---|---|
| #2602 | Good partial fix for oversized observer payload overflow. It does not fully close #2643 token/cost explosion, but it should reduce one death-loop class. Mergeable if accepted as partial reliability work. |
| #2593 | Chroma Windows uvx metacharacter fix. Likely worth landing, but coordinate with existing Windows Chroma PRs to avoid duplicate/competing fixes. |
| #2596 | Bundle-size / better-auth externalization. Merge after packaging dependency policy is clear, because externalization increases reliance on `plugin/node_modules`. |
| #2599 | Windows PID reuse guard. Useful but larger than Batch A; review after smaller Windows launch fixes land. |

## Do not merge as-is / split first

- #2536: important Chroma orphan cleanup direction, but currently conflicting and too broad. Ask for a focused PR touching `ChromaMcpManager` + targeted tests first.
- Older conflicting PRs that are superseded by #2594/#2598/#2613 should be marked superseded or asked to rebase, otherwise the Windows queue will stay noisy.

## Suggested next action

Merge Batch A first, then run a fresh release-candidate smoke around:

- Windows Git Bash hook startup
- MCP search startup on Windows without `sh`
- fresh plugin cache with no `node_modules/zod`
- Bedrock/Vertex host env present but worker using its own provider config
- server-beta generation job startup with modes loaded

This would cut the reviewer burden sharply: most of the queue either lands, becomes superseded, or moves into a smaller owner-driven follow-up.

cc @thedotmack

**Comment by YOMXXX** [comment]
Execution update for the reviewer queue:

- #2610: pushed the missing context-generator no-external-zod assertion; local `npm run build` passed.
- #2602: pushed the remaining prompt-truncation defensive guard and rebuilt `worker-service.cjs`; local `npm run build` passed. `npm run typecheck` still fails on existing errors outside this PR scope.
- #2616: pushed the missing summary-prompt redaction-marker guidance, a focused `buildSummaryPrompt` test, and rebuilt `worker-service.cjs`; local `npm run build` plus a `tsx` summary-prompt sanity check passed.

I also mirrored this in discussion #2648 so reviewers have the PR roadmap and execution status in one place.

**Comment by YOMXXX** [comment]
Maintainer decision request — consolidated follow-up for the open reviewer queue (2026-05-27).

There has not been a maintainer response since the last execution update. I rechecked the open YOMXXX PRs: all 14 still report `MERGEABLE`, and the three PRs that had concrete review-summary gaps now have follow-up commits and verification comments.

Suggested next maintainer action:

**Merge first if you want the smallest high-value batch:**

- #2610 — root fix for the recurring `Cannot find module 'zod/v3'` worker/server-beta/context-generator packaging failure. Remaining guardrail was added and `npm run build` passed.
- #2602 — prevents observer oversized-prompt death loops and avoids destructive pending-observation clearing on overflow. Remaining truncation edge case was fixed and `npm run build` passed.
- #2594 — replaces the shell-based MCP launcher with a cross-platform Node launcher for #2461.
- #2592 — adds the missing transcript-watcher build target for #2450.
- #2599 — fixes Windows supervisor PID token capture for #2578.

**Then merge low-risk cleanup/refactor PRs:**

- #2595 — marketplace sync script hardening.
- #2596 — externalize `better-auth` from worker/server-beta bundles.
- #2632 — unify worker DB init through `MigrationRunner`.
- #2633 — consolidate `parseJsonArrayColumn`.

**Hold for explicit product/release decision rather than silent backlog:**

- #2593 / #2598 — both touch Windows hook/MCP launch behavior and may be superseded by a more direct launcher strategy.
- #2597 — useful as package-install fallback, but #2610 is the cleaner zod root fix if we want self-contained bundles.
- #2616 / #2627 — opt-in feature PRs; both have review gaps addressed, but they are larger behavioral changes than the bugfix batch.

If there is only bandwidth for one decision: please either merge the first batch above or name the blocker PR number(s), and I can keep narrowing the review surface from there.

**Comment by gorkem2020** [comment]
Adding a v13.4.0 data point for both the packaging and supervisor parts of this cluster, in case it helps prioritize the merges.

Environment: Linux, installed from the `thedotmack` marketplace, upgraded via `claude plugin update claude-mem@thedotmack` (upgrade path, not a fresh install).

**Packaging (#2610 / #2650 still needed):** after updating to v13.4.0 the worker failed to boot with `Cannot find module 'zod/v3'`. The new version's cache directory had no `node_modules/`. `package.json` declares zod and the tree-sitter grammars as runtime dependencies, but `claude plugin update` runs no install step, so `require()` fails on the first hook invocation. Workaround was `cd ~/.claude/plugins/cache/thedotmack/claude-mem/13.4.0 && npm install` then respawning the worker. So the latest release still ships without a working dependency story on the upgrade path, not just on fresh install.

**Supervisor:** on the upgrade path specifically, a stale worker daemon from a previously deleted cache directory kept running via Linux file-handle persistence (the binary stays mapped in memory after the old cache dir is removed). The SessionStart hook saw a live PID in the supervisor state and logged `Worker PID file points to a live process, skipping duplicate spawn`, so it never launched the new version. The stale worker survived two full editor restarts and the plugin update itself, and had to be killed manually before v13.4.0 could take over. It might be worth having the spawn check validate that the running worker's executable still exists on disk (resolve `/proc/<pid>/exe`, or compare the running cmdline against the current cache dir) rather than trusting PID liveness alone.

Happy to provide logs if useful.

**Comment by thedotmack** [comment]
Closing this tracking issue: of the 8-PR Windows/packaging/supervisor cluster, the supervisor fix shipped as #2768, the Windows MCP launcher as #2807, the Windows Chroma spawn as #2847, and the EACCES pipe fix as #2865 (#2725). The packaging/node_modules question continues on #2831 with review feedback on #2531/#2710. Superseded PRs were closed today with individual explanations.
