### ISSUE TITLE
v13.9.1: two more missing-bundle modules — SessionStore.js (backfill fails at startup) + .install-version marker ("runtime not yet set up")

### ISSUE THREAD

**Issue by Robin528919** [thedotmack/claude-mem#3092]
## Summary

Beyond the observation sync failure already documented in #3091, v13.9.1 ships with **two additional missing files** that break independent features.

---

### Symptom

On every worker startup, the Chroma backfill pipeline logs:

```
[ERROR] [CHROMA_SYNC] Failed to initialize backfill resources
  ResolveMessage: Cannot find module '../sqlite/SessionStore.js'
  from '...13.9.1/scripts/worker-service.cjs'
```

### Root cause

In `worker-service.cjs`:

```js
var vC;
function c2() {
  return vC || (vC = l2()("../sqlite/SessionStore.js").SessionStore), vC;
}

// called at worker startup:
static async backfillAllProjects(e) {
  let r, n;
  try {
    const s = c2();      // ← throws ResolveMessage — SessionStore.js missing from bundle
    r = e ?? new s;
    n = new Ta("claude-mem");
  } catch (s) {
    g.error("CHROMA_SYNC", "Failed to initialize backfill resources", {}, s);
    // ...
  }
}
```

`sqlite/SessionStore.js` exists as bundled code in 13.8.1 but was moved to an external module in 13.9.1 without being included in the bundle output.

**Note:** in practice `backfillAllProjects` is always called with the existing `dbManager.getSessionStore()` as argument `e`, so `new s` is never reached — but `c2()` itself throws before `r = e ?? new s` even evaluates, causing the entire backfill to be skipped.

### Workaround (until 13.9.2)

Create `sqlite/SessionStore.js` at both plugin cache paths:

```js
// sqlite/SessionStore.js
import { Database } from 'bun:sqlite';
import { join } from 'path';
import { homedir } from 'os';
import { mkdirSync, readFileSync } from 'fs';

function resolveDataDir() {
  if (process.env.CLAUDE_MEM_DATA_DIR) return process.env.CLAUDE_MEM_DATA_DIR;
  const base = join(homedir(), '.claude-mem');
  try {
    const cfg = JSON.parse(readFileSync(join(base, 'settings.json'), 'utf-8'));
    const env = cfg.env ?? cfg;
    if (env.CLAUDE_MEM_DATA_DIR) return env.CLAUDE_MEM_DATA_DIR;
  } catch {}
  return base;
}

export class SessionStore {
  db;
  constructor(dbPath) {
    const dataDir = resolveDataDir();
    const resolvedPath = dbPath ?? join(dataDir, 'claude-mem.db');
    mkdirSync(dataDir, { recursive: true });
    this.db = new Database(resolvedPath);
    this.db.run('PRAGMA journal_mode = WAL');
    this.db.run('PRAGMA synchronous = NORMAL');
    this.db.run('PRAGMA foreign_keys = ON');
  }
  close() {
    try { this.db?.close(); } catch {}
  }
}
```

Paths:
- `~/.claude/plugins/cache/thedotmack/claude-mem/13.9.1/sqlite/SessionStore.js`
- `~/.codex/plugins/cache/claude-mem-local/claude-mem/13.9.1/sqlite/SessionStore.js`

Restart the worker after creating the file. Backfill will complete normally:
```
[INFO ] [CHROMA_SYNC] Smart backfill complete {project=..., synced=..., watermarks=...}
```

---

### Symptom

Every Claude Code session start prints:

```
claude-mem: runtime not yet set up - run: npx claude-mem@latest install
```

Running `npx claude-mem@latest install` does not fix it because `npx claude-mem@latest` resolves to **v12.4.7** on npm, while the marketplace-installed plugin is **v13.9.1**. The install script writes a version-mismatched marker (or none at all) so the check keeps failing.

### Root cause

`scripts/version-check.js` (lines ~177–193) reads:

```js
const markerPath = join(ROOT, '.install-version');
if (!existsSync(markerPath)) {
  emit("claude-mem: runtime not yet set up - run: npx claude-mem@latest install");
  return;
}
const { version } = JSON.parse(readFileSync(markerPath, 'utf-8'));
if (version !== EXPECTED_VERSION) {
  emit("claude-mem: runtime not yet set up ...");
}
```

`ROOT` = the plugin's cache directory. The `.install-version` file is written by `npx claude-mem@latest install`, but because npm still serves v12.4.7 as `@latest`, the file either:
- isn't created (old install script doesn't know about 13.9.1's requirement), or
- is created with `{"version":"12.4.7"}` which fails the version check.

### Workaround

```bash
echo '{"version":"13.9.1"}' > \
  ~/.claude/plugins/cache/thedotmack/claude-mem/13.9.1/.install-version
```

Verify:
```bash
node ~/.claude/plugins/cache/thedotmack/claude-mem/13.9.1/scripts/version-check.js && echo "OK"
# → OK  (silent = working)
```

### Fix suggestion

Either:
- **Publish 13.9.1 to npm** so `npx claude-mem@latest install` picks up the correct version, or
- **Have the marketplace installer write `.install-version`** when it drops plugin files into the cache directory, or
- **Make `version-check.js` resilient** — if the file is missing, attempt to write it rather than bailing out.

---

## Fix suggestion for all three missing modules (#3091 + this issue)

Add all three files to the bundler entry points (or keep them inlined as in 13.8.1):

```
sqlite/observations/files.js   ← #3091
sqlite/SessionStore.js         ← Bug 1 above
```

And ensure `.install-version` is written by the marketplace install flow.

**Comment by alexnettor** [comment]
Confirming this is still present in **13.9.2** (not just 13.9.1), so the fix mentioned in the title as "until 13.9.2" didn't land.

Environment: Windows 11, Claude Code, plugin installed via marketplace on 2026-06-30, bun 1.3.14.

Every observation write logs:
```
[ERROR] [CHROMA_SYNC] Failed to initialize backfill resources ResolveMessage: Cannot find module '../sqlite/SessionStore.js' from 'C:\Users\<user>\.claude\plugins\marketplaces\thedotmack\plugin\scripts\worker-service.cjs'
[ERROR] [CHROMA_SYNC] Backfill failed (non-blocking) {}
[ERROR] [CHROMA] SDK chroma sync failed, continuing without vector search {obsId=..., ...}
```
on effectively every stored observation (dozens of occurrences in a single day's log), not just at startup.

I checked both install locations to see if the module is just missing at that specific path:
- `~/.claude/plugins/cache/thedotmack/claude-mem/13.9.2/scripts/` — no `sqlite/` subfolder at all
- `~/.claude/plugins/marketplaces/thedotmack/plugin/scripts/` — same, no `sqlite/` subfolder

The only place `SessionStore` exists in the repo is as TS source: `src/services/sqlite/SessionStore.ts`. It never made it into either shipped bundle (cache install or marketplace plugin dir), which suggests the build step that's supposed to emit `scripts/sqlite/SessionStore.js` isn't running as part of the marketplace release/packaging, not just a one-off packaging miss in 13.9.1.

Agree with the fix suggestion — bundling `sqlite/` alongside `worker-service.cjs` (or inlining it like 13.8.1 did) would resolve this for both install paths.

**Comment by lasha-che** [comment]
Both bugs confirmed still present on **13.9.2** (fresh `npx claude-mem install`, Linux/Ubuntu, Bun 1.3.14, marketplace layout `~/.claude/plugins/marketplaces/thedotmack`) — so "Workaround (until 13.9.2)" turned out to be optimistic.

**Bug 1 (SessionStore.js backfill):** identical `ResolveMessage: Cannot find module '../sqlite/SessionStore.js'` at every worker start, plus per-observation `[CHROMA] SDK chroma sync failed` (cross-ref #3107). On marketplace installs, where the repo sources ship alongside the plugin, there's a simpler workaround than the stub class — symlink the real sources and let Bun's require resolve `.js` → `.ts`:

```bash
ln -sfn ../src/services/sqlite ~/.claude/plugins/marketplaces/thedotmack/plugin/sqlite
npx claude-mem restart
```

This restores full backfill *and* per-observation vector sync (verified: `[CHROMA_SYNC] Syncing observation {observationId=…, documentCount=4}`), and unlike the stub it keeps the complete `SessionStore` implementation. Details in https://github.com/thedotmack/claude-mem/issues/3107#issuecomment-4869602249.

**Bug 2 (`.install-version` marker):** also reproduces on 13.9.2 — no `.install-version` exists anywhere under the marketplace dir after install, and running `scripts/version-check.js` directly prints `claude-mem: runtime not yet set up - run: npx claude-mem@latest install` despite a healthy, fully working worker.
