### ISSUE TITLE
opencode plugin loading error: "Plugin export is not a function"

### ISSUE THREAD

**Issue by rahuliyer95** [thedotmack/claude-mem#2854]
## Before submitting

- [x] I searched [existing issues](https://github.com/thedotmack/claude-mem/issues) and confirmed this is not a duplicate

---

### Summary

After installing claude-mem for opencode, the plugin fails to load on **every** startup and memory capture never initializes:

```
ERROR service=plugin path=file:///…/.config/opencode/plugins/claude-mem.js error=Plugin export is not a function failed to load plugin
```

This appears to be a **regression in 13.4.1/13.4.2**: per #2832, the OpenCode plugin *loads* fine on **13.4.0** (that issue is about capture, and assumes loading works). On **13.4.2** it no longer loads at all.

### Environment

- claude-mem: **13.4.2**
- opencode: **1.16.2**
- OS: macOS

### Steps to reproduce

1. Install claude-mem for opencode (so the opencode plugin entrypoint is loaded).
2. Start opencode.
3. Observe the error in `~/.local/share/opencode/log/*.log`.

### Root cause

opencode's plugin loader imports the module and treats **every export** as a plugin function ([docs](https://opencode.ai/docs/plugins): "a module that exports one or more plugin functions"), throwing if any export is not a function.

The shipped `dist/opencode-plugin/index.js` (v13.4.2) exports two **arrays** alongside the plugin function:

```js
export {
  jf as ClaudeMemPlugin,            // function ok
  M_ as REAL_OPENCODE_EVENT_TYPES,  // array  -> not a function
  L_ as REGISTERED_OPENCODE_HOOKS,  // array  -> not a function
  C_ as default,                    // function ok
  Nf as parseSearchResponse         // function ok
};
```

where `M_ = ["session.idle","session.deleted"]` and `L_ = ["tool.execute.after", ...]`. When the loader reaches those array exports it aborts. These exports (the hook auto-registry constants) appear to be what regressed loading between 13.4.0 and 13.4.2, note #2832's proposed fix also touches `REGISTERED_OPENCODE_HOOKS`.

### Workaround

Editing the shipped file to export only functions fixes loading (reverts on reinstall):

```js
export { jf as ClaudeMemPlugin, jf as default, Nf as parseSearchResponse };
```

### Suggested fix

Stop exporting the internal `REAL_OPENCODE_EVENT_TYPES` / `REGISTERED_OPENCODE_HOOKS` constants from the opencode plugin entrypoint — keep them module-internal or move them to a separate (non-plugin) module. Only plugin function(s) should be exported from `dist/opencode-plugin/index.js`.

### Related

- #2832 — OpenCode plugin loads but captures nothing on opencode 1.16.2 (the *next* problem once loading is fixed; confirms loading worked on 13.4.0).
- #1845 — earlier load-time crash on the opencode plugin (different error, `_zod.def`, older versions).
- #2670 — install/registration fix (separate from export shape).

**Comment by K-S-Manikandan** [comment]
**Still reproducible on 13.12.4 / opencode 1.18.10** (confirmed Aug 1, 2026)

```
opencode 1.18.10
claude-mem 13.12.4 (installed 2026-07-28)
```

Every startup fails with:

```
message="failed to load plugin" path=file:///home/manikandan/.config/opencode/plugins/claude-mem.js error="Plugin export is not a function"
```

Root cause confirmed — the shipped bundle still exports non-function constants from the plugin entrypoint:

```js
// dist/opencode-plugin/index.js (13.12.4)
export{ag as ClaudeMemPlugin, y$ as REAL_OPENCODE_EVENT_TYPES, x$ as REGISTERED_OPENCODE_HOOKS, b$ as default, cg as parseSearchResponse}
```

`REAL_OPENCODE_EVENT_TYPES` and `REGISTERED_OPENCODE_HOOKS` are arrays. opencode's loader treats every export as a plugin function and aborts. I verified that stripping them to function-only exports makes the module load (3 exports: `ClaudeMemPlugin`, `default`, `parseSearchResponse` — all functions).

Proposed fix (minimal, revert-safe):
```js
export{ag as ClaudeMemPlugin, b$ as default, cg as parseSearchResponse}
```

Keep the two constants module-internal (or move to a non-plugin entrypoint) so the plugin entrypoint only exports functions. Works locally; survives until the next `npx claude-mem install --ide opencode` reinstall, which restores the buggy bundle. Happy to open a PR if useful.

**Comment by toniher** [comment]
I can confirm myself.

This is how opencode (with DeepSeek V4 Flash Free) suggested me as a solution. It created a wrapper function for me:

# claude-mem opencode plugin fix

Date: 2026-08-03
Environment: opencode 1.18.11 (global config `~/.config/opencode`), claude-mem v13.13.0 bundle, worker daemon on port 37700.

## Symptom

claude-mem never captured or searched memory in opencode. `~/.local/share/opencode/log/opencode.log` showed on every run:

```
failed to load plugin path=.../plugins/claude-mem.js error="Plugin export is not a function"
```

## Root cause (two independent bugs)

1. **Loader rejection of non-function exports.** claude-mem's bundled plugin module exports helper objects
   (`REAL_OPENCODE_EVENT_TYPES`, `REGISTERED_OPENCODE_HOOKS`) in addition to the plugin function
   (`ClaudeMemPlugin` / `default`). opencode's loader (`getLegacyPlugins` in
   `packages/opencode/src/plugin/index.ts`) iterates **every** module export and throws
   `TypeError("Plugin export is not a function")` on the first non-function export, so the whole plugin
   failed to load.

2. **Worker port mismatch.** The bundle builds its server URL from
   `37877 + (uid % 100)` (37877 for uid 1000), but the claude-mem worker daemon listens on port **37700**
   (see `~/.claude-mem/worker.pid`). Even if the plugin loaded, observation/search calls would hit a dead port.

## Fix

Plugin config was moved out of the `plugins/` directory into `vendor/` so nothing under `plugins/` is
auto-discovered, and a wrapper module exposes only the plugin function while fixing the port.

Files:

| Path | Role |
|------|------|
| `vendor/claude-mem.js` | The original claude-mem bundle, moved verbatim from `plugins/claude-mem.js` |
| `vendor/claude-mem-wrapper.js` | Wrapper: reads worker port, sets `CLAUDE_MEM_SERVER_PORT`, re-exports only the plugin function |
| `opencode.jsonc` | `plugin` entry now points at `./vendor/claude-mem-wrapper.js` |

`vendor/claude-mem-wrapper.js`:

```js
import { readFileSync } from "node:fs"
import { homedir } from "node:os"
import { join } from "node:path"

let workerPort = process.env.CLAUDE_MEM_SERVER_PORT
if (!workerPort) {
  try {
    const info = JSON.parse(readFileSync(join(homedir(), ".claude-mem", "worker.pid"), "utf8"))
    if (info.port) workerPort = String(info.port)
  } catch {}
}
if (!workerPort) workerPort = "37700"
process.env.CLAUDE_MEM_SERVER_PORT = workerPort

const cm = await import("./claude-mem.js")
export default cm.default
```

Why this works:
- `process.env.CLAUDE_MEM_SERVER_PORT` is set via top-level await **before** the bundle module body
  evaluates (the bundle reads the env var while building its defaults object).
- The wrapper's only export is `default` (the plugin function), so every export is a function and the
  loader's `getLegacyPlugins` check passes.
- Bundles were moved out of `plugins/` to avoid any directory auto-discovery picking up the original file.

## Verification

All confirmed by importing the wrapper with bun (same dynamic-import path opencode uses):

- Module exports are all functions.
- `claude_mem_search` tool queries the worker on 37700 and returns real observations.
- A simulated assistant `chat.message` was captured into the memory DB (~1s) and is searchable.

## How to test after a restart

opencode reads config only at startup, so quit and restart opencode, then:

1. Ask the assistant to use the `claude_mem_search` tool (e.g. "search claude-mem memory for ...").
   It should return observations instead of "claude-mem worker is not running".
2. Work normally; observations from the session are recorded and surface in later searches.

Notes:
- The worker daemon does not need restarting (already running on 37700).
- If `~/.claude-mem/worker.pid` is ever unreadable, the wrapper falls back to port 37700.
- A single probe observation from the verification step remains in the memory DB; harmless.

**Comment by chris-yyau** [comment]
**Still broken on the latest release — verified today (2026-08-09): `claude-mem@13.14.0` + opencode `1.18.15`, reproduced from a fresh npm tarball, with a working minimal workaround.**

Reproduced from the published artifact, not a stale install:

- `claude-mem@13.14.0` (published 2026-08-08): extracted `dist/opencode-plugin/index.js` directly from the npm tarball
- opencode `1.18.15` (macOS)
- `npx claude-mem status` shows the worker itself is healthy (Version 13.14.0) — only the opencode plugin bundle is affected

The fresh 13.14.0 bundle fails identically:

```
level=ERROR message="failed to load plugin" path=.../plugins/claude-mem.js error="Plugin export is not a function"
```

**Loader contract is unchanged in 1.18.15.** The minified check in the 1.18.15 binary (`uk`/`hk`/`gV`) iterates `Object.values(module)` and requires every export to be a function or a `{ server: fn }` object; `gV` is `v => typeof v === "function"`. The 13.14.0 bundle still ends with:

```js
export{cg as ClaudeMemPlugin,x$ as REAL_OPENCODE_EVENT_TYPES,b$ as REGISTERED_OPENCODE_HOOKS,k$ as default,ug as parseSearchResponse};
```

The two `as const` arrays trip the check. They are exported only because `tests/integrations/opencode-plugin-contract.test.ts` imports them — a test dependency that forces a public export which violates the runtime contract. (Confirmed in the 13.14.0 source: `export const REAL_OPENCODE_EVENT_TYPES`, `export const REGISTERED_OPENCODE_HOOKS` in `src/integrations/opencode-plugin/index.ts`.)

**Verified workaround (running locally right now):** strip the two array names from the bundle's export statement — the entry then exports only functions and opencode loads the plugin cleanly (no load error in the opencode log; hooks register):

```js
// before
export{cg as ClaudeMemPlugin,x$ as REAL_OPENCODE_EVENT_TYPES,b$ as REGISTERED_OPENCODE_HOOKS,k$ as default,ug as parseSearchResponse};
// after
export{cg as ClaudeMemPlugin,k$ as default,ug as parseSearchResponse};
```

**Suggested upstream fix:** move `REAL_OPENCODE_EVENT_TYPES` / `REGISTERED_OPENCODE_HOOKS` into a submodule (e.g. `src/integrations/opencode-plugin/contract.ts`), import them into `index.ts` for internal use, and have the contract test import from the submodule. The plugin entry file then exports only functions and passes the loader on every opencode version.

Same root cause as #3328 and #3330 (reported against opencode 1.17.x); this thread covers 13.4.1 → 13.14.0, so the regression has been live for ~5 minor releases.

**Comment by thedotmack** [comment]
Consolidating into #3611 (plan-23). The root cause and fix sequencing are tracked there alongside the rest of the cluster — please follow that issue for progress.
