### ISSUE TITLE
fix(#1215): PR #1229 fallback path points to marketplace source, not installed cache — hooks still fail when CLAUDE_PLUGIN_ROOT unset

### ISSUE THREAD

**Issue by jacobcxdev** [thedotmack/claude-mem#1242]
## Summary

PR #1229 attempted to fix the `CLAUDE_PLUGIN_ROOT` injection issue (#1215) by adding a shell-level fallback in `hooks.json`. Unfortunately the fallback path is wrong, so hooks still fail for anyone affected by the upstream Claude Code bug.

## The problem with the current fallback

The merged fix uses:

```sh
_R="${CLAUDE_PLUGIN_ROOT}"; [ -z "$_R" ] && _R="$HOME/.claude/plugins/marketplaces/thedotmack/plugin"
```

But `~/.claude/plugins/marketplaces/thedotmack/plugin` is the **plugin source directory** — it does not contain `worker-service.cjs` or `node_modules`. The actual runtime files live in the **cache directory**:

```
~/.claude/plugins/cache/thedotmack/claude-mem/<version>/
```

When `CLAUDE_PLUGIN_ROOT` is unset (i.e., the exact scenario this fix targets), the fallback resolves to a path that doesn't have the worker, so the hook fails the same way as before.

## Repro

On macOS with Claude Code v2.1.5x, `CLAUDE_PLUGIN_ROOT` is not injected for Stop hooks (and on Linux, for all hook types). With the current fallback:

```
node: cannot find module '…/marketplaces/thedotmack/plugin/scripts/bun-runner.js'
```

The file doesn't exist at that path.

## Working workaround

Replace `${CLAUDE_PLUGIN_ROOT}` with the absolute cache path at install time:

```bash
VERSION=$(ls ~/.claude/plugins/cache/thedotmack/claude-mem/ | sort -V | tail -1)
sed -i '' "s|\${CLAUDE_PLUGIN_ROOT}|$HOME/.claude/plugins/cache/thedotmack/claude-mem/$VERSION|g" \
  ~/.claude/plugins/cache/thedotmack/claude-mem/$VERSION/hooks/hooks.json \
  ~/.claude/plugins/cache/thedotmack/claude-mem/$VERSION/.mcp.json
```

Must be re-applied after each update (version in path changes).

## Suggested fix

The fallback should resolve to the cache path, not the marketplace path. One approach: at install/setup time (in `setup.sh` or `smart-install.js`), rewrite `hooks.json` and `.mcp.json` in-place, replacing `${CLAUDE_PLUGIN_ROOT}` with the actual cache directory path. This way the files are self-contained with no env var dependency at all.

Alternatively, `bun-runner.js`'s `fixBrokenScriptPath` (introduced in #1229) could serve as the sole fix if the detection heuristic is made more robust — but the shell-level fallback to the marketplace path should be removed since it gives false confidence.

## Environment

- macOS, Claude Code v2.1.5x
- claude-mem v10.4.4
- Upstream bug: anthropics/claude-code#24529

**Comment by Shockang** [comment]
Confirmed on current `main` as of 2026-03-08: `plugin/hooks/hooks.json` still falls back directly to the marketplace source path when `CLAUDE_PLUGIN_ROOT` is unset.

I opened PR #1301 with a focused fix:
- probe installed cache paths first (`~/.config/claude/plugins/cache/...` and `~/.claude/plugins/cache/...`)
- keep the marketplace path only as the final fallback
- add a regression test that asserts the hook commands include the cache-path fallback

I also shell-validated the new fallback snippet against both cache-present and cache-missing HOME layouts before opening the PR.

**Comment by jacobcxdev** [comment]
@thedotmack if you could prioritise getting this fixed, I would be highly appreciative. Every update breaks my config and I have to go and patch it manually. Thanks.

**Comment by Dmdv** [comment]
## Still happening in v10.6.2 (March 2026)

This issue is still present. On a fresh install via the Claude Code plugin marketplace:

- **Installed path**: `~/.claude/plugins/cache/thedotmack/claude-mem/10.6.2/`
- **Fallback path** (hardcoded): `~/.claude/plugins/marketplaces/thedotmack/plugin/`

The fallback directory exists but is missing most scripts:

```
# Fallback scripts/ has only:
bun-runner.js, claude-mem, CLAUDE.md

# Real install scripts/ has:
bun-runner.js, claude-mem, CLAUDE.md,
context-generator.cjs, mcp-server.cjs, smart-install.js,
statusline-counts.js, worker-cli.js, worker-service.cjs, worker-wrapper.cjs
```

When `CLAUDE_PLUGIN_ROOT` is unset (which happens during startup), all 3 `SessionStart` hooks fall back to the stale path and fail:

```
SessionStart:startup hook error
SessionStart:startup hook error
SessionStart:startup hook error
```

The error (visible with `claude --verbose`):
```
Module not found "/Users/<user>/.claude/plugins/marketplaces/thedotmack/plugin/scripts/worker-service.cjs"
```

**Workaround**: Manually copy the missing scripts and symlink `node_modules` from the cache install to the fallback path. But this breaks on every plugin update.

**Suggested fix**: Either remove the fallback path entirely (rely on `CLAUDE_PLUGIN_ROOT`) or keep the fallback path in sync during installation.

**Comment by alessandropcostabr** [comment]
## Additional confirmation from Windows 11 + claude-mem 10.6.3

Same issue confirmed. The hardcoded path in `worker-cli.js` prevents auto-start on plugin system installations:

```javascript
var P = join(homedir(), ".claude", "plugins", "marketplaces", "thedotmack");
// Actual install: ~/.claude/plugins/cache/thedotmack/claude-mem/10.6.3/
```

### Impact chain

This causes a cascade of failures:
1. `worker-cli.js start` → "Worker script not found" (silent)
2. MCP server logs `Worker not available` with no explanation
3. All MCP tools (`search`, `get_observations`, etc.) return `fetch failed`

### Workaround

Directory junction bridges the gap:

```powershell
New-Item -ItemType Junction `
  -Path "$HOME\.claude\plugins\marketplaces\thedotmack\plugin\scripts" `
  -Target "$HOME\.claude\plugins\cache\thedotmack\claude-mem\10.6.3\scripts"
```

### Additional: `hooks.json` SessionEnd hardcodes port 37777

Line 77 in `hooks/hooks.json` has `port:37777` hardcoded instead of reading from settings/env. This breaks when using a non-default port (e.g., to work around zombie sockets per #415 / #1603).

See also #1609 (closing as duplicate of this issue).

**Comment by CyanoTex** [comment]
https://github.com/thedotmack/claude-mem/issues/1522

Honestly, Claude-mem's useful, but fuck, it needs this fixed bad.

**Comment by thedotmack** [comment]
Closed during the April 2026 backlog cleanup. The underlying bug is now tracked in #1906, which is the single canonical issue being addressed by the maintainer. Thanks for taking the time to report — your symptoms and repro are captured in the consolidated ticket.
