### ISSUE TITLE
tree-sitter native binding fails on Node 24 / Windows; consider WASM (web-tree-sitter)

### ISSUE THREAD

**Issue by lotheral** [thedotmack/claude-mem#2410]
v13.0.1 install on Windows 11 + Node 24.14.0 fails because tree-sitter 0.25.0 ships no prebuilt for ABI 137. node-gyp fallback build fails with MSBuild errors. Result: smart_outline / smart_search / smart_unfold all return "Could not parse" silently. Repro: Trivial 9-line .py file → smart_outline → "Could not parse".

Suggestion: switch to web-tree-sitter (WASM-based). Used by Understand-Anything plugin; works cross-platform with no native build, no Node ABI version pinning. tree-sitter-python.wasm is already shipped in the same packages.

**Comment by spallen** [comment]
Same failure on macOS (Apple Silicon, Darwin 25.4.0) with claude-mem 13.1.0 — confirms this is not Windows-specific, it's a `tree-sitter@0.25.0` + Node 24 incompatibility across platforms.

**Reproducer (macOS)**
- Node: `v24.13.1` (nvm-managed)
- Bun: `1.3.5`
- Plugin: `claude-mem@13.1.0` from the Claude Code marketplace cache (`~/.claude/plugins/cache/thedotmack/claude-mem/13.1.0/`)
- Install path: `bun install` inside the plugin dir (workaround for #2407, which ships v13.0.0 without bundled `node_modules`)

**Symptom**
After `bun install` completes and `bun pm trust tree-sitter ...` is invoked, `tree-sitter@0.25.0`'s `node-gyp` fallback compile fails with C++20-feature errors against Node 24's V8 headers:

```
/Users/.../node-gyp/24.13.1/include/node/cppgc/macros.h:51:1:
  error: unknown type name 'concept'
   51 | concept IsStackAllocatedType =

/Users/.../node-gyp/24.13.1/include/node/v8-memory-span.h:168:35:
  error: no type named 'contiguous_iterator_tag' in namespace 'std';
         did you mean 'output_iterator_tag'?
  168 |     using iterator_concept = std::contiguous_iterator_tag;

/Users/.../node-gyp/24.13.1/include/node/cppgc/macros.h:52:5:
  error: use of undeclared identifier 'requires'
   52 |     requires { typename T::IsStackAllocatedTypeMarker; };
```

These are cppgc / iterator-concept features that need C++20 + a recent enough toolchain. The default `node-gyp` configuration (older C++ standard) cannot parse them. Same root cause as Windows MSBuild — V8's `cppgc/macros.h` requires C++20 across all platforms.

**Useful detail for the WASM migration suggestion**
Only the `tree-sitter` runtime itself ships *without* prebuilds. The grammars (`tree-sitter-bash`, `tree-sitter-c`, `@tree-sitter-grammars/tree-sitter-yaml`, etc.) DO ship prebuilds for all 6 platforms (`darwin-{arm64,x64}`, `linux-{arm64,x64}`, `win32-{arm64,x64}`). So a fix that swaps just the runtime to WASM (`web-tree-sitter`) while keeping the grammars as `.node` files may be tractable — though the grammar `.wasm` files mentioned in the original report would be the cleaner long-term move.

**Bun behavior observation**
`bun pm trust <packages>` aborts on the first failed build and **does not persist** any `trustedDependencies` changes when the install script fails. Atomic rollback — useful to know when reproducing: failed attempts leave no orphan state. Re-running `bun pm untrusted` after the failure shows the original full list.

**Workaround tried**
None successful on Node 24. Switching the global Node version to 22 LTS likely fixes it but is invasive for the dev environment.

**Impact**
Same as Windows report: `smart_outline` / `smart_search` / `smart_unfold` degraded silently. Memory writes (`save_observation`) and text search work normally — only multi-language AST features are affected.

**Comment by GuanHukd** [comment]
Reproducing on Windows 11 with Node v24.14.0 and claude-mem 13.2.0. Adding the specific MSBuild error in case it helps
   narrow the fix path — the failure is the C++20-flag issue from #2280, not just a missing prebuilt:

  cl : command line warning D9025: overriding '/std:c++20' with '/std:c++17'
    [...\tree_sitter_runtime_binding.vcxproj]
  C:\Users<u>\AppData\Local\node-gyp\Cache\24.14.0\include\node\v8config.h(13,1):
    error C1189: #error: "C++20 or later required."

  Toolchain is fine (VS2026 BuildTools 18.4.11605.240, Python 3.14.3, node-gyp 12.3.0, MSBuild found and invoked). Root
  cause is `tree-sitter@0.25.0`'s `binding.gyp` forcing `/std:c++17`, which overrides the C++20 default that Node 24's
  V8 headers now require — same root cause as #2280, just expressed via MSBuild on Windows instead of clang on macOS.

  The `CXXFLAGS=-std=c++20 bun install` workaround from #2280 doesn't apply on Windows/MSVC — there `cflags_cc` in
  `binding.gyp` controls it, so a manual patch would be replacing `/std:c++17` with `/std:c++20` in
  `node_modules/tree-sitter/binding.gyp` (and every `tree-sitter-*` grammar's binding.gyp). Fragile and wiped on any
  reinstall.

  Upstream fix options that would actually stick for users: bump (or remove) the `"overrides": { "tree-sitter":
  "^0.25.0" }` pin in `plugin/package.json` to a tree-sitter release that builds on Node 24, or move to
  `web-tree-sitter` (WASM) as proposed in the title of this issue — the WASM path also sidesteps the missing-prebuilt +
  node-gyp fallback problem for users without a working MSVC/Xcode toolchain.

**Comment by thedotmack** [comment]
Consolidating into #2379 (plan-04). The root cause and fix sequencing are tracked there alongside the rest of the cluster — please follow that issue for progress.
